package stackjava.com.sbsecurityhibernate.entities;
// Generated Sep 8, 2019 5:55:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * InfoSendSms generated by hbm2java
 */
@Entity
@Table(name = "info_send_sms", catalog = "giai_phap_sms")
public class InfoSendSms implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idInfoSendSms;
	private String numberPhone;
	private String content;
	private int status;
	private int typeSend;
	private String sender;
	private int sendNow;
	private Date dateTimeSend;
	private int repeatTime;
	private Date createDate;
	private Date updateDate;
	private Set<OtpInput> otpInputs = new HashSet<OtpInput>(0);

	public InfoSendSms() {
	}

	public InfoSendSms(String numberPhone, String content, int status, int typeSend, String sender, int sendNow,
			Date dateTimeSend, int repeatTime, Date createDate, Date updateDate) {
		this.numberPhone = numberPhone;
		this.content = content;
		this.status = status;
		this.typeSend = typeSend;
		this.sender = sender;
		this.sendNow = sendNow;
		this.dateTimeSend = dateTimeSend;
		this.repeatTime = repeatTime;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public InfoSendSms(String numberPhone, String content, int status, int typeSend, String sender, int sendNow,
			Date dateTimeSend, int repeatTime, Date createDate, Date updateDate, Set<OtpInput> otpInputs) {
		this.numberPhone = numberPhone;
		this.content = content;
		this.status = status;
		this.typeSend = typeSend;
		this.sender = sender;
		this.sendNow = sendNow;
		this.dateTimeSend = dateTimeSend;
		this.repeatTime = repeatTime;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.otpInputs = otpInputs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_info_send_sms", unique = true, nullable = false)
	public Integer getIdInfoSendSms() {
		return this.idInfoSendSms;
	}

	public void setIdInfoSendSms(Integer idInfoSendSms) {
		this.idInfoSendSms = idInfoSendSms;
	}

	@Column(name = "number_phone", nullable = false, length = 15)
	public String getNumberPhone() {
		return this.numberPhone;
	}

	public void setNumberPhone(String numberPhone) {
		this.numberPhone = numberPhone;
	}

	@Column(name = "content", nullable = false, length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "type_send", nullable = false)
	public int getTypeSend() {
		return this.typeSend;
	}

	public void setTypeSend(int typeSend) {
		this.typeSend = typeSend;
	}

	@Column(name = "sender", nullable = false, length = 15)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "send_now", nullable = false)
	public int getSendNow() {
		return this.sendNow;
	}

	public void setSendNow(int sendNow) {
		this.sendNow = sendNow;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_time_send", nullable = true, length = 19)
	public Date getDateTimeSend() {
		return this.dateTimeSend;
	}

	public void setDateTimeSend(Date dateTimeSend) {
		this.dateTimeSend = dateTimeSend;
	}

	@Column(name = "repeat_time", nullable = true)
	public int getRepeatTime() {
		return this.repeatTime;
	}

	public void setRepeatTime(int repeatTime) {
		this.repeatTime = repeatTime;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infoSendSms")
	public Set<OtpInput> getOtpInputs() {
		return this.otpInputs;
	}

	public void setOtpInputs(Set<OtpInput> otpInputs) {
		this.otpInputs = otpInputs;
	}

}
