package stackjava.com.sbsecurityhibernate.entities;
// Generated Sep 8, 2019 5:55:56 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;

/**
 * OtpInput generated by hbm2java
 */
@Entity
@Table(name = "otp_input", catalog = "giai_phap_sms")
public class OtpInput implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer otpInputId;
	private InfoSendSms infoSendSms;
	private Users users;
	private String otp;
	private int status;
	private int type;
	private Date createDate;
	private Date updateDate;

	public OtpInput() {
	}

	public OtpInput(InfoSendSms infoSendSms, Users users, String otp, int status, int type, Date createDate,
			Date updateDate) {
		this.infoSendSms = infoSendSms;
		this.users = users;
		this.otp = otp;
		this.status = status;
		this.type = type;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "otp_input_id", unique = true, nullable = false)
	public Integer getOtpInputId() {
		return this.otpInputId;
	}

	public void setOtpInputId(Integer otpInputId) {
		this.otpInputId = otpInputId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_info_send_sms", nullable = false)
	public InfoSendSms getInfoSendSms() {
		return this.infoSendSms;
	}

	public void setInfoSendSms(InfoSendSms infoSendSms) {
		this.infoSendSms = infoSendSms;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "otp", nullable = false, length = 8)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@CreationTimestamp
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
